# -*- coding: utf-8 -*-
"""Tugas Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgpArhayPZf2IFTqRYDQFDzCC-PHwusL

1. Memuat Data
"""

import pandas as pd #import library
df = pd.read_csv('movie_sample_dataset (1).csv') #membaca data csv

"""2. Memeriksa Data"""

df.head() #menunjukkan baris awal data
print(df.info()) #menunjukkan info data

"""3. Membersihkan Data"""

df_cleaned = df.dropna(subset=['gross', 'budget']) #Menghapus baris yang memiliki nilai NaN di kolom 'gross' dan 'budget'
df_cleaned = df_cleaned[(df_cleaned['budget'] >= 0) & (df_cleaned['gross'] >= 0)] #menghapus nilai negatif
df_cleaned.replace("N/A", pd.NA, inplace=True) #mengganti nilai "N/A" atau teks yang setara menjadi NaN
df_cleaned = df_cleaned.dropna() #Drop baris yang memiliki NaN setelah penggantian "N/A"

"""4. Transformasi Data"""

df_cleaned['budget'] = pd.to_numeric(df_cleaned['budget'], errors='coerce') #Mengubah tipe data 'budget' menjadi numerik
df_cleaned['gross'] = pd.to_numeric(df_cleaned['gross'], errors='coerce') #Mengubah tipe data 'gross' menjadi numerik
genres_split = df_cleaned['genres'].str.split('|', expand=True) #Memisahkan genre yang bergabung dalam satu kolom
df_cleaned = pd.concat([df_cleaned, genres_split], axis=1) # Menggabungkan kembali dataframe dengan kolom genre yang dipisah
df_cleaned.columns = list(df_cleaned.columns[:len(df_cleaned.columns)-genres_split.shape[1]]) + [f'genre_{i+1}' for i in range(genres_split.shape[1])] #memberi nama kolom genre yang terpisah
# Normalisasi teks di kolom yang relevan: 'color', 'country', 'language'
df_cleaned['language'] = df_cleaned['language'].str.lower()
df_cleaned['country'] = df_cleaned['country'].str.lower()
df_cleaned['color'] = df_cleaned['color'].str.lower()

"""5. Menyimpan Data"""

#Menyimpan Data yang Telah Dibersihkan dan Ditransformasi
output_path = 'movie_dataset_cleaned.csv'
df_cleaned.to_csv(output_path, index=False)